export enum DateRangeType {
  WEEK = 'WEEK',
  MONTH = 'MONTH',
  QUARTER = 'QUARTER',
  YTD = 'YTD',
  YEARLY = 'YEARLY',
  CUSTOM = 'CUSTOM',
  THIS_WEEK = 'THIS_WEEK',
  THIS_MONTH = 'THIS_MONTH',
  THIS_YEAR = 'THIS_YEAR',
}
