export const OFFNET_VENDOR_NAME_LIST = [
  '123.NET',
  '2PiFi',
  '702 Communications',
  'Accel Net',
  'ACS (Alaska Communications)',
  'Altice (Cablevision, Lightpath)',
  'Altice (Suddenlink)',
  'Armstrong',
  'Arvig',
  'Astound Wholesale (Wave Wholesale)',
  'AT&T',
  'AT&T Investment Build',
  'Beyond Reach',
  'Bluebird',
  'Bluepeak (Vast Broadband)',
  'Breezeline (Atlantic Broadband)',
  'C Spire',
  'CableOne - Sparklight',
  'Cox',
  'Crown Castle (Lightower, FPL FiberNet, Wilcon, Sunesys)',
  'Dobson',
  'Everstream',
  'Ezee Fiber',
  'Fiberlight',
  'Firstlight',
  'FirstDigital Telecom',
  'Frontier',
  'Granite',
  'Great Plains Communications',
  'GTT',
  'Hargray',
  'Indatel',
  'iTel Networks',
  'Logix Fiber Networks (Alpheus)',
  'LS Networks',
  'Lumen (CenturyLink)',
  'Lumen (Level 3 On-Net Investment Building)',
  'Lumen (Level 3 On-Net Non-Investment Building)',
  'Lumen (Level 3 Wave Circuits)',
  'Lumen (Level 3/TWT)',
  'Mediacom',
  'MetroNet',
  'Mid-Atlantic Broadband',
  'Midcontinent',
  'NITEL',
  'NOA-NET',
  'PenTeleData',
  'Ritter Communications',
  'Segra (Lumos, Spirit, PalmettoNet)',
  'Shentel',
  'Spectrum (Brighthouse)',
  'Spectrum (Charter)',
  'Spectrum (Time Warner Cable)',
  'Stratus',
  'Syringa',
  'Unitas Global',
  'Unite Private Networks (UPN)',
  'Uniti Fiber',
  'Verizon Business',
  'Verizon Telco',
  'Vexus',
  'Windstream',
  'WOW!',
  'Zayo',
  'Ziply',
];
